# Generated by Django 5.2.7 on 2025-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours'), ('evalue', 'Évalué')], default='soumis', max_length=20)),
                ('note_finale', models.FloatField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lien_github', models.URLField(blank=True, max_length=255, null=True)),
                ('lien_figma', models.URLField(blank=True, max_length=255, null=True)),
                ('lien_presentation', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
