spring.application.name=auth-web-api
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8083}

jwt.issuer=web-secure
jwt.secret=MySuperSecretKeyForJwtSigning1234567890
jwt.expiration-ms=3600000

# Postgres config
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka client registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
